services:
  db:
    build: ./db
    env_file:
      - .env
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s

  web:
    build: ./web
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"

volumes:
  dbdata:
    external: true